/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HumanStoriesRouteImport } from './routes/human-stories'
import { Route as CapitalIntelligenceRouteImport } from './routes/capital-intelligence'
import { Route as IndexRouteImport } from './routes/index'

const HumanStoriesRoute = HumanStoriesRouteImport.update({
  id: '/human-stories',
  path: '/human-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const CapitalIntelligenceRoute = CapitalIntelligenceRouteImport.update({
  id: '/capital-intelligence',
  path: '/capital-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capital-intelligence': typeof CapitalIntelligenceRoute
  '/human-stories': typeof HumanStoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capital-intelligence': typeof CapitalIntelligenceRoute
  '/human-stories': typeof HumanStoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capital-intelligence': typeof CapitalIntelligenceRoute
  '/human-stories': typeof HumanStoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/capital-intelligence' | '/human-stories'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/capital-intelligence' | '/human-stories'
  id: '__root__' | '/' | '/capital-intelligence' | '/human-stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapitalIntelligenceRoute: typeof CapitalIntelligenceRoute
  HumanStoriesRoute: typeof HumanStoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/human-stories': {
      id: '/human-stories'
      path: '/human-stories'
      fullPath: '/human-stories'
      preLoaderRoute: typeof HumanStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capital-intelligence': {
      id: '/capital-intelligence'
      path: '/capital-intelligence'
      fullPath: '/capital-intelligence'
      preLoaderRoute: typeof CapitalIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapitalIntelligenceRoute: CapitalIntelligenceRoute,
  HumanStoriesRoute: HumanStoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
