/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemsIntelligenceRouteImport } from './routes/systems-intelligence'
import { Route as OpportunityGraphRouteImport } from './routes/opportunity-graph'
import { Route as MoralIntelligenceRouteImport } from './routes/moral-intelligence'
import { Route as MissionControlRouteImport } from './routes/mission-control'
import { Route as HumanStoriesRouteImport } from './routes/human-stories'
import { Route as CapitalIntelligenceRouteImport } from './routes/capital-intelligence'
import { Route as IndexRouteImport } from './routes/index'

const SystemsIntelligenceRoute = SystemsIntelligenceRouteImport.update({
  id: '/systems-intelligence',
  path: '/systems-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityGraphRoute = OpportunityGraphRouteImport.update({
  id: '/opportunity-graph',
  path: '/opportunity-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const MoralIntelligenceRoute = MoralIntelligenceRouteImport.update({
  id: '/moral-intelligence',
  path: '/moral-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanStoriesRoute = HumanStoriesRouteImport.update({
  id: '/human-stories',
  path: '/human-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const CapitalIntelligenceRoute = CapitalIntelligenceRouteImport.update({
  id: '/capital-intelligence',
  path: '/capital-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capital-intelligence': typeof CapitalIntelligenceRoute
  '/human-stories': typeof HumanStoriesRoute
  '/mission-control': typeof MissionControlRoute
  '/moral-intelligence': typeof MoralIntelligenceRoute
  '/opportunity-graph': typeof OpportunityGraphRoute
  '/systems-intelligence': typeof SystemsIntelligenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capital-intelligence': typeof CapitalIntelligenceRoute
  '/human-stories': typeof HumanStoriesRoute
  '/mission-control': typeof MissionControlRoute
  '/moral-intelligence': typeof MoralIntelligenceRoute
  '/opportunity-graph': typeof OpportunityGraphRoute
  '/systems-intelligence': typeof SystemsIntelligenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capital-intelligence': typeof CapitalIntelligenceRoute
  '/human-stories': typeof HumanStoriesRoute
  '/mission-control': typeof MissionControlRoute
  '/moral-intelligence': typeof MoralIntelligenceRoute
  '/opportunity-graph': typeof OpportunityGraphRoute
  '/systems-intelligence': typeof SystemsIntelligenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capital-intelligence'
    | '/human-stories'
    | '/mission-control'
    | '/moral-intelligence'
    | '/opportunity-graph'
    | '/systems-intelligence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capital-intelligence'
    | '/human-stories'
    | '/mission-control'
    | '/moral-intelligence'
    | '/opportunity-graph'
    | '/systems-intelligence'
  id:
    | '__root__'
    | '/'
    | '/capital-intelligence'
    | '/human-stories'
    | '/mission-control'
    | '/moral-intelligence'
    | '/opportunity-graph'
    | '/systems-intelligence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapitalIntelligenceRoute: typeof CapitalIntelligenceRoute
  HumanStoriesRoute: typeof HumanStoriesRoute
  MissionControlRoute: typeof MissionControlRoute
  MoralIntelligenceRoute: typeof MoralIntelligenceRoute
  OpportunityGraphRoute: typeof OpportunityGraphRoute
  SystemsIntelligenceRoute: typeof SystemsIntelligenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/systems-intelligence': {
      id: '/systems-intelligence'
      path: '/systems-intelligence'
      fullPath: '/systems-intelligence'
      preLoaderRoute: typeof SystemsIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity-graph': {
      id: '/opportunity-graph'
      path: '/opportunity-graph'
      fullPath: '/opportunity-graph'
      preLoaderRoute: typeof OpportunityGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moral-intelligence': {
      id: '/moral-intelligence'
      path: '/moral-intelligence'
      fullPath: '/moral-intelligence'
      preLoaderRoute: typeof MoralIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human-stories': {
      id: '/human-stories'
      path: '/human-stories'
      fullPath: '/human-stories'
      preLoaderRoute: typeof HumanStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capital-intelligence': {
      id: '/capital-intelligence'
      path: '/capital-intelligence'
      fullPath: '/capital-intelligence'
      preLoaderRoute: typeof CapitalIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapitalIntelligenceRoute: CapitalIntelligenceRoute,
  HumanStoriesRoute: HumanStoriesRoute,
  MissionControlRoute: MissionControlRoute,
  MoralIntelligenceRoute: MoralIntelligenceRoute,
  OpportunityGraphRoute: OpportunityGraphRoute,
  SystemsIntelligenceRoute: SystemsIntelligenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
